### ISSUE TITLE
LP查询详细页面添加返回网站主页按钮

### ISSUE THREAD

**Issue by LobotomyCorporation** [jackdaw3/eve-starweb#1]
https://eve.starweb.cc/lpstore
https://eve.starweb.cc/serenity/lpstore
进入LP查询网页后是否可以在左上角或者右上角添加返回主页 https://eve.starweb.cc/ 的按钮？

**Comment by alexdongsh** [comment]
是有的 可能不太明显，就是左上角那个蓝色的星系图标，点一下就能回到主页

**Comment by LobotomyCorporation** [comment]
> 是有的 可能不太明显，就是左上角那个蓝色的星系图标，点一下就能回到主页

啊哈，看到了
![Snipaste_2024-09-05_17-37-35](https://github.com/user-attachments/assets/1b3b4d17-52bb-4b8b-922e-32a8f5a45d31)
